spring:
  application:
    name: CPP-EXECUTION-SERVICE

  cloud:
    consul:
      host: ${CODEHORN_CONSUL_HOST:localhost}
      discovery:
        service-name: CPP-EXECUTION-SERVICE
        healthCheckPath: /health-check   # ðŸ‘ˆ Custom health check path
        healthCheckInterval: 15s